version: '3'

services:
  pure-fa-om-exporter:
    image: quay.io/purestorage/pure-fa-om-exporter:v1.0.2
    command: 
      - '--host=0.0.0.0'
      - '--port=9490'
    depends_on: 
      - prometheus
    ports:
      - 9490:9490

  prometheus:
    image: prom/prometheus
    command:
      - '--storage.tsdb.retention=60d'
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - prometheus-data:/prometheus
    configs:
      - source: prometheus.config
        target: /etc/prometheus/prometheus.yml
        mode: 0420
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin!
    depends_on: 
      - pure-fa-om-exporter
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards

volumes:
  prometheus-data:
  grafana-data:
  
configs:
  prometheus.config:
    file: ./prometheus/prometheus.yml

