apiVersion: apps/v1
kind: Deployment
metadata:
  name: pure-fa-om-exporter
  namespace: monitoring
  labels:
    app: pure-fa-exporter
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: pure-fa-exporter
  template:
    metadata:
      labels:
        app: pure-fa-exporter
    spec:
      containers:
      - name: pure-fa-om-exporter
        image: quay.io/purestorage/pure-fa-ome
        args:
          - '--workers=2'
        ports:
        - name: web
          containerPort: 9491
      restartPolicy: Always
