apiVersion: v1
kind: Service
metadata:
    name: pure-fa-exporter
    namespace: monitoring
spec:
    selector:
        app: pure-fa-exporter
    type: NodePort
    ports:
    - port: 9491
      targetPort: 9491
      nodePort: 30491
