global:
  scrape_interval:     60s
  scrape_timeout:      50s
scrape_configs:
  - job_name: 'purestorage-fa'
    metrics_path: /metrics/array
    authorization:
      credentials: 64f736be-9b7c-d7a5-4f85-16716969c1b1
    params:
      endpoint: ['10.21.229.28']

    static_configs:
    - targets:
      - pure-fa-om-exporter:9490
      labels:
        location: US
        site: TestSite
        instance: FlashArray1
        env: 'Test Lab'

  - job_name: 'purestorage-fa_volumes'
    metrics_path: /metrics/volumes
    authorization:
      credentials: 64f736be-9b7c-d7a5-4f85-16716969c1b1
    params:
      endpoint: ['10.21.229.28']

    static_configs:
    - targets:
      - pure-fa-om-exporter:9490
      labels:
        location: US
        site: TestSite
        instance: FlashArray1
        env: 'Test Lab'

  - job_name: 'purestorage-fa_hosts'
    metrics_path: /metrics/hosts
    authorization:
      credentials: 64f736be-9b7c-d7a5-4f85-16716969c1b1
    params:
      endpoint: ['10.21.229.28']

    static_configs:
    - targets:
      - pure-fa-om-exporter:9490
      labels:
        location: US
        site: TestSite
        instance: FlashArray1
        env: 'Test Lab'
 
