global:
  scrape_interval:     60s
  scrape_timeout:      50s
scrape_configs:
  - job_name: 'purestorage-fa'
    metrics_path: /metrics/array
    authorization:
      credentials: 60db5575-f825-735a-fa09-61a70de2badd
    params:
      endpoint: 10.225.104.19

    static_configs:
    - targets:
      - pure-fa-om-exporter:9490
      labels:
        location: RSA
        site: BFTC
        instance: cbmgpurea110
        env: 'BFTC-NPR'

  - job_name: 'purestorage-fa_volumes'
    metrics_path: /metrics/volumes
    authorization:
      credentials: 60db5575-f825-735a-fa09-61a70de2badd
    params:
      endpoint: 10.225.104.19

    static_configs:
    - targets:
      - pure-fa-om-exporter:9490
      labels:
        location: RSA
        site: BFTC
        instance: cbmgpurea110
        env: 'BFTC-NPR'

  - job_name: 'purestorage-fa_hosts'
    metrics_path: /metrics/hosts
    authorization:
      credentials: 60db5575-f825-735a-fa09-61a70de2badd
    params:
      endpoint: 10.225.104.19

    static_configs:
    - targets:
      - pure-fa-om-exporter:9490
      labels:
        location: RSA
        site: BFTC
        instance: cbmgpurea110
        env: 'BFTC-NPR'
        
  - job_name: 'purestorage-fa_pods'
    metrics_path: /metrics/pods
    authorization:
      credentials: 60db5575-f825-735a-fa09-61a70de2badd
    params:
      endpoint: 10.225.104.19

    static_configs:
    - targets:
      - pure-fa-om-exporter:9490
      labels:
        location: RSA
        site: BFTC
        instance: cbmgpurea110
        env: 'BFTC-NPR'
 
#  - job_name: 'purestorage-fa_directories'
#    metrics_path: /metrics/directories
#    authorization:
#      credentials: <YOUR_API_TOKEN>
#    params:
#      endpoint: [<YOUR_FLASHARRAY_IP>]

#    static_configs:
#    - targets:
#      - pure-fa-om-exporter:9490
#      labels:
#        location: US
#        site: TestSite
#        instance: FlashArray1
#        env: 'Test Lab'
 

#  - job_name: 'purestorage-fa2'
#    metrics_path: /metrics/array
#    authorization:
#      credentials: <YOUR_API_TOKEN>
#    params:
#      endpoint: [<YOUR_FLASHARRAY_IP>]

#    static_configs:
#    - targets:
#      - pure-fa-om-exporter:9490
#      labels:
        location: US
        site: TestSite
        instance: FlashArray2
        env: 'Test Lab'

  - job_name: 'purestorage-fa2_volumes'
    metrics_path: /metrics/volumes
    authorization:
      credentials: <YOUR_API_TOKEN>
    params:
      endpoint: [<YOUR_FLASHARRAY_IP>]

    static_configs:
    - targets:
      - pure-fa-om-exporter:9490
      labels:
        location: US
        site: TestSite
        instance: FlashArray2
        env: 'Test Lab'

  - job_name: 'purestorage-fa2_hosts'
    metrics_path: /metrics/hosts
    authorization:
      credentials: <YOUR_API_TOKEN>
    params:
      endpoint: [<YOUR_FLASHARRAY_IP>]

    static_configs:
    - targets:
      - pure-fa-om-exporter:9490
      labels:
        location: US
        site: TestSite
        instance: FlashArray2
        env: 'Test Lab'
        
  - job_name: 'purestorage-fa2_pods'
    metrics_path: /metrics/pods
    authorization:
      credentials: <YOUR_API_TOKEN>
    params:
      endpoint: [<YOUR_FLASHARRAY_IP>]

    static_configs:
    - targets:
      - pure-fa-om-exporter:9490
      labels:
        location: US
        site: TestSite
        instance: FlashArray2
        env: 'Test Lab'
 
  - job_name: 'purestorage-fa2_directories'
    metrics_path: /metrics/directories
    authorization:
      credentials: <YOUR_API_TOKEN>
    params:
      endpoint: [<YOUR_FLASHARRAY_IP>]

    static_configs:
    - targets:
      - pure-fa-om-exporter:9490
      labels:
        location: US
        site: TestSite
        instance: FlashArray2
#        env: 'Test Lab'
 
