apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: pure-fa-probe
  namespace: monitoring
spec:
  jobName: pure-fa-probe
  prober:
    url: pure-fa-exporter-svc:9490
    path: /metrics/pods
  interval: 15s
  targets:
    staticConfig:
      static:
        - x90a
        - x90b
        - x70a
